GoogleChromeLabs/squoosh

config/critters-webpack-plugin.js
config/html-webpack-inline-critical-css-plugin.js
package.json
src/index.html
src/lib/fix-pmc.js
src/style/index.scss
webpack.config.js

This adds a new plugin (which I think could be released on its own, and I have a funny name for). It plugs into the output of `html-webpack-plugin`, finds inline & external stylesheets, inlines them, then trims out selectors & rules not used by the document.
In this app, the effect is a drop from 13kb to 1.2kb of critical CSS.
(note: currently targeted at `app-skeleton` branch)
Still to do:
/cc @surma

CSS Inlining

---

codecs/mozjpeg_enc/package-lock.json
src/components/app/custom-els/FileDrop/index.ts
src/components/app/custom-els/FileDrop/missing-types.d.ts
src/components/app/custom-els/FileDrop/styles.css
src/components/app/index.tsx
src/components/app/style.scss
src/components/output/index.tsx

* Defines a `<file-drop>` element that lets you filter on File mimetypes via an `accepts` attr (it can take image/png, or wildcards.). When a matching file is found, the first file in the dataTransfer object is attached to a new 'onFileDrop event.
* Implements `<file-drop>` in app, it wraps the entire app Component and hooks up with the logic to take the file element and load it when the 'onFileDrop' event triggers.
Current known issue, the entire App is position absolute, so I've just made my `<file-drop>` default to display: block, width & height 100%... kinda doesn't fell right.
The file-drop element also emulates the pseudo classes that drag and drop is supposed to support and it applies them only once on dragEnter and dragLeave to avoid lots of transitions and layout recalcs etc. …

Adding in Drag and Drop support to fix #45

---

src/components/output/index.tsx

DO NOT MERGE.
This is blocked on https://github.com/GoogleChromeLabs/squoosh/pull/39. I'll rebase once that merges.
Ready for review though. One line change.

Allow mouse wheel on two-up handle. Fixes #49

---

package-lock.json
package.json
src/codecs/browser-jpeg/encoder.ts
src/codecs/browser-jpeg/options.ts
src/codecs/browser-png/encoder.tsx
src/codecs/encoders.ts
src/codecs/generic/quality-option.tsx
src/codecs/mozjpeg/options.tsx
src/components/app/index.tsx
src/components/options/index.tsx
src/lib/util.ts

Adding the browser's JPEG & PNG encoders. Also added file size indicator.
Things are getting interesting now! This shows how much better MozJPEG is than Chrome's encoder. I also leaned that Chrome's PNG encoder is better than OSX's screenshot tool.
I'll make a PR for adding WebP too, but I'll need to figure out a way to feature test that.

Adding native encoders

---

src/codecs/browser-webp/encoder.ts
src/codecs/browser-webp/options.ts
src/codecs/encoders.ts
src/components/app/index.tsx
src/components/options/index.tsx

I made this a separate PR as it involves async feature tests. This will probably be the only encoder that has a feature test, but the patterns may be reusable for detecting decode support.

Adding browser's webp encoder

---

src/codecs/browser-bmp/encoder.ts
src/codecs/browser-gif/encoder.ts
src/codecs/browser-jp2/encoder.ts
src/codecs/browser-pdf/encoder.ts
src/codecs/browser-tiff/encoder.ts
src/codecs/browser-webp/encoder.ts
src/codecs/encoders.ts
src/codecs/generic/util.ts
src/components/app/index.tsx
src/components/options/index.tsx

I've asked Edge for a list of what they support. If there's anything missing, I'll add it.

All the encoders that Chrome/Safari/Firefox support out of the box.

---

codecs/webp_enc/webp_enc.d.ts
src/codecs/encoders.ts
src/codecs/webp/Encoder.worker.ts
src/codecs/webp/encoder.ts
src/codecs/webp/options.tsx
src/components/App/index.tsx
src/components/Options/index.tsx

Right now `webp/Encoder.worker.ts` is a copy/paste job that's crying out for abstraction, but I feel that might be wasted work as we start adding options to encoders.
I've started playing with C++ and emscripten bindings https://github.com/GoogleChromeLabs/squoosh/compare/webp-encode-integrate...webp-encode-options - it feels like this might be a better way forward, especially as we need to pass option structs into the encoder (and perhaps the other way, for getting default options).
I don't have strong feelings when it comes to merging this with the copy-paste job, and filing a v1 issue to fix that across codecs, or blocking this PR on it.

Basic webp encoding integration

---

src/components/Output/custom-els/TwoUp/index.ts
src/components/Output/custom-els/TwoUp/missing-types.d.ts
src/components/Output/custom-els/TwoUp/styles.css
src/components/Output/index.tsx

The designs show the two-up working vertically on mobile, so I implemented that.

Vertical two-up

---

src/components/App/index.tsx

The ZX quantiser is slow, so we *need this*.
Happy to delay merging this until https://github.com/GoogleChromeLabs/squoosh/pull/124 is resolved, since it touches a lot of the same stuff.

Avoid preprocessing images that have already been preprocessed.

---

src/lib/PointerTracker/index.ts
src/lib/PointerTracker/missing-types.d.ts

Low priority, as squoosh doesn't need this.

Adding changed points and coalescing to pointer tracker. Fixes #133.

---

src/components/App/index.tsx
src/components/App/result-cache.ts

Fixes #87.
I was chatting to @developit about #146 - copy to other side, and he pointed out that implementing would be a lot easier if we already had a results cache, so I went ahead and made one.
Do not merge, but please review - this is based on the UI branch as I wanted to use the shallow compare util that @developit wrote.

Adding encoding results cache

---

src/components/Output/custom-els/PinchZoom/index.ts
src/components/Output/index.tsx

Do not merge, as this is not based on master, but please review!
Fixes #129.

Pinch zoom features

---

package-lock.json
package.json
src/codecs/preprocessors.ts
src/codecs/resize/options.tsx
src/codecs/resize/resize.ts
src/components/App/index.tsx
src/components/Options/index.tsx
src/components/Options/style.scss
src/components/Output/index.tsx
src/components/Output/style.scss
src/lib/util.ts

Part of #131, although at some point I'd like us to support non-browser resize methods, but this solves a lot of the use cases.
I decided that resizing is a pretty important part of image compression, especially if you're grabbing something taken by a phone.
Anyway, here it is.
It isn't based on master, so don't merge yet, but I'm interested in reviews, including reviews of the interaction.

Adding resize preprocessor

---

src/components/Output/custom-els/TwoUp/index.ts
src/components/Output/custom-els/TwoUp/missing-types.d.ts

Fixes #105 
Repositions the handle for TwoUp when the element resizes.
I have 2 questions:
1. Do we have constraints on Browser compatibility? Should I include a polyfill for ResizeObserver? 
2. Making TS happy with ResizeObserver was a bit elaborate and I'm a newbie in TS - please advise if there's a better approach!

Reposition the TwoUp handle on resize

---

package-lock.json
package.json
src/codecs/browser-webp/decoder.ts
src/codecs/decoders.ts
src/codecs/resize/resize.ts
src/codecs/webp/decoder.ts
src/components/App/index.tsx
src/components/App/result-cache.ts
src/components/Output/index.tsx
src/lib/missing-types.d.ts
src/lib/util.ts

This turned out to be a bigger job than I thought. The resizing I was using is behind a flag in Chrome, so I switched it out for a simpler method.
While I was at it, I created fallbacks for all `createImageBitmap` usage, and removed our usage of `ImageBitmap` and replaced it with the more universally-supported `ImageData`. We were doing a lot of conversion between the two types anyway, so switching to just one makes more sense.

Creating fallbacks for all ImageBitmap usage & refactoring.

---

src/codecs/mozjpeg/options.tsx
src/codecs/webp/options.tsx
src/components/Options/index.tsx
src/components/Options/style.scss
src/components/Output/custom-els/RangeInput/index.ts
src/components/Output/custom-els/RangeInput/missing-types.d.ts
src/components/Output/custom-els/RangeInput/styles.css

Fixes the style issues from #143 (except button colors, which relies on stuff not on the `custom-range-inputs` branch).

Design review fixes

---

src/components/Output/index.tsx
src/components/Output/style.scss

Regressed in 059c80c05d491f9f9019ffabe4f5a290ed63a266. I guess this is why we should have tests 😀.

Fixing resize again. Fixes #183.

---

src/components/App/index.tsx
src/components/App/style.scss
src/components/intro/index.tsx
src/components/intro/style.scss

I'm in the process of doing the UI for the intro screen, but this seemed worth committing.
I've moved the intro into its own component, but along the way I fixed it so the image can display before the initial compression is ready. This improves performance especially with large images.
Until the initial compression is ready, the source image data will be used.

Improving image open time

---

src/codecs/resize/options.tsx
src/codecs/resize/resize.ts
src/components/App/index.tsx
src/components/Options/index.tsx
src/lib/util.ts

**DO NOT MERGE but please review** (not based on master)
No longer fails when loading SVG.
Also, I made the resize preprocessor vector-aware, so it'll do the resizing in SVG if the source is SVG.

Handle vectors

---

src/custom-els/RangeInput/index.ts

This fixes the `.disabled` property reflection for range-input. Previously, only the `disabled` attribute worked.
Fixes #142.

Fix <range-input disabled>

---

src/components/App/index.tsx
src/components/compress/index.tsx
src/components/intro/index.tsx
src/lib/SnackBar/index.ts
src/lib/SnackBar/styles.css
webpack.config.js

* Snackbar default timeout removed & replaced with "dismiss" button (otherwise, large WASM errors were lost, and it'd be nice if folks could copy those for bug reports).
* Copying settings across can now be undone.

Snackbar defaults & copy undo

---

src/index.html

Not normally something I'd do, but I've ended up in cases where the viewport is zoomed in and it's difficult to zoom out.
Since pinch zooming is our main interaction, it makes sense to disable the browser's.
This doesn't work in iOS10 though https://stackoverflow.com/a/38852262/123395.

Prevent browser pinch-zoom

---

package-lock.json
package.json
src/index.ts
webpack.config.js

Preload test

---

src/manifest.json

Change orientation to "any" - allowing tablet pwa users to use the app in any screen orientation.

Fix #268 - change orientation to "any" from "portrait" in manifest.json

---

src/components/intro/style.scss

This is to fix the [Accidental click & drag on home screen loads logo image](https://github.com/GoogleChromeLabs/squoosh/issues/274) issue. Microsoft Edge doesn't support the second block of CSS in [this file](https://github.com/GoogleChromeLabs/squoosh/blob/master/src/style/reset.scss) to prevent dragging. 
While testing this I also noticed it's not just the logo image that can be dragged in Edge on the homepage, the sample images under the "Or try one of these:" section also had the same issue, although it's not as big of an issue. At first I thought this was intentional but then I noticed on other browsers those can't be dragged either so to make it consistent I prevented dragging on those too.

Preventing images from being dragged in Edge

---

src/codecs/processor.ts
src/codecs/rotate/processor.ts
src/components/compress/index.tsx

Spotted that we were loading our rotation code when we didn't need to.
Also, our worker timeout was set to 1 second. It's supposed to be 10 and I have no idea when/how I managed to fuck that up.

Rotation optimise. Fixes #362

---

src/components/Options/style.scss

When using dark browser themes the text-fields' text-color becomes white, so the text in those white background text-fields is unreadable.
Patched text-color so that it now is readable.
Before:
After:

Fixed blank text-fields with dark browser theme

---

src/components/App/index.tsx

It's a shame that this ends up in our main bundle, but can't think of a better way around it.
It's so small that putting it in its own module doesn't seem worth it.

Preventing zoom in iOS Safari.

---

src/codecs/rotate/processor.ts

This pull request modifies how rotate/processor.ts copies the image data to & from the WASM work buffer.
The Rust rotate implementation merged from #438 adds a 4 byte padding to the beginning of the WASM. Currently rotate/processor.ts copies the image data to offset `0` instead of `4`, and reads the output buffer from offset `bytesPerImage` instead of `bytesPerImage + 4`. As a result the rotated images may have some artifacts. In the following example the artifacts are visible along some sides of the rotated versions (e.g. top left corner of the 270° one):
This pull request also makes a minor modification to how many pages are needed for the WASM buffer. Currently `4` gets added to `bytesPerImage * 2 / (64 * 1024)`, while the `4` should probably be added before the division.

Fix buffer offset/size calculations in rotate/processor.ts

---

codecs/optipng/build.sh

Specifically the size shrinks from 108K to 46K :smiley: 
I'm hopeful this just works, as the project already uses MODULARIZE (so nothing can access internals from outside, which is dangerous with closure). Is there a test suite I should run locally? Or will CI here run tests?

Use closure in optipng build, which shrinks the JS to less than half
