- .babelrc
This should fix the WC issues. I've verified that the classes are left in-tact in the compiled output.
Fixes #13.
> Don't transpile ES Classes.

- src/lib/PointerTracker/index.ts
I should have done this before merging. Please forgive my trespasses.
> Using @bind

- src/components/output/custom-els/TwoUp/index.ts
- src/components/output/custom-els/TwoUp/missing-types.d.ts
- src/components/output/custom-els/TwoUp/styles.css
- src/components/output/index.tsx
- src/missing-types.d.ts
> Integrating two-up

- codecs/mozjpeg_enc/package-lock.json
- codecs/webp_enc/package-lock.json
- package-lock.json
- package.json
- src/lib/codec-wrappers/codec.ts
- src/lib/codec-wrappers/mozjpeg-enc.ts
With these fixes in place I have the build running locally on a chromebook.
> Fix codec integration

- package-lock.json
- package.json
- src/components/output/custom-els/PinchZoom/index.ts
- src/components/output/custom-els/TwoUp/index.ts
- src/components/output/custom-els/TwoUp/missing-types.d.ts
- src/lib/PointerTracker/index.ts
- src/lib/codec-wrappers/mozjpeg-enc.ts
- src/lib/util.ts
- tslint.json
Here’s what tslint currently complains about if this change got merged:
<details>
```
husky > pre-commit (node v10.3.0)
> squoosh@0.0.0 lint /Users/surma/src/github.com/GoogleChromeLabs/squoosh
> tslint -c tslint.json 'src/**/*.{ts,js}'
Warning: The 'no-boolean-literal-compare' rule requires type information.
No valid rules have been specified for JavaScript files
ERROR: src/components/output/custom-els/PinchZoom/index.ts[27, 21]: Spaces before function parens are disallowed
ERROR: src/components/output/custom-els/PinchZoom/index.ts[32, 21]: Spaces before function parens are disallowed
ERROR: src/components/output/custom-els/PinchZoom/index.ts[37, 41]: Missing trailing comma
ERROR: src/components/output/custom-els/PinchZoom/index.ts[45, 16]: Spaces before function parens are disallowed …
```
> Switch to tslint and run it as commit hook

- src/components/app/index.tsx
- src/components/output/index.tsx
- src/lib/util.ts
This is some stuff I did as I was fixing the second-file-load issue.
Feel free to throw it back at me.
> Refactorings

- src/components/App/index.tsx
- src/components/Options/index.tsx
Fixes https://github.com/GoogleChromeLabs/squoosh/issues/121 and https://github.com/GoogleChromeLabs/squoosh/issues/120.
> Quant fixes

- src/components/App/index.tsx
> fix broken file renaming for file names with dot

- src/components/App/result-cache.ts
Resurrecting this after Github closed it and blamed me 😄.
I've fixed the move-to-start bit, but also gone for array methods rather than moving things around manually, as it feels more idiomatic.
> Result cache LRU

- src/components/output/custom-els/MultiPanel/index.ts
- src/components/output/custom-els/MultiPanel/styles.css
This PR is the same thing for #24 but against master.
All of code review feedback from #24 should have been addressed, and typescript errors resolved.
> Add multi-panel component

- src/components/App/index.tsx
- src/components/App/result-cache.ts
- src/components/Options/index.tsx
- src/components/Output/index.tsx
- src/lib/util.ts
**Do not merge**. Not based on master.
> Edge file constructor fix

- src/components/Output/custom-els/PinchZoom/index.ts
- src/components/Output/style.scss
> Center the image canvas in PinchZoom

- src/lib/util.ts
> Fixing webp sniffing. Fixes #178.

- src/codecs/generic/quality-option.tsx
- src/codecs/imagequant/options.tsx
- src/codecs/webp/options.tsx
- src/codecs/webp/styles.scss
- src/components/Output/custom-els/RangeInput/index.ts
- src/components/Output/custom-els/RangeInput/missing-types.d.ts
- src/components/Output/custom-els/RangeInput/styles.css
I'm very jetlagged so maybe this is simpler for very bad reasons.
> Taking a swing at the range input

- src/components/Output/custom-els/TwoUp/styles.css
> Edge gets confused about custom properties in @supports.

- src/components/App/index.tsx
- src/components/App/style.scss
A bit of belt-and-braces that users may never see. A spinner if the user selects a file before the main app has loaded.
> App loading indicator

- src/codecs/generic/quality-option.tsx
- src/codecs/imagequant/options.tsx
- src/codecs/mozjpeg/options.tsx
- src/codecs/optipng/options.tsx
- src/codecs/resize/options.tsx
- src/codecs/webp/options.tsx
- src/components/App/custom-els/FileDrop/index.ts
- src/components/App/index.tsx
- src/components/App/style.scss
- src/components/Options/index.tsx
- src/components/Output/custom-els/PinchZoom/index.ts
- src/components/Output/index.tsx
- src/components/compress/index.tsx
- src/components/compress/result-cache.ts
- src/components/compress/style.scss
- src/components/intro/index.tsx
- src/custom-els/RangeInput/index.ts
- src/lib/PointerTracker/index.ts
- src/lib/initial-util.ts
- src/lib/util.ts
Also improving the transition from intro to compressor.
> Lazy-loading the main part of the app

- src/lib/util.ts
> Edge encode fix

- src/components/Options/index.tsx
- src/components/Options/style.scss
- src/components/compress/index.tsx
- src/components/results/index.tsx
- src/components/results/style.scss
- src/lib/icons.tsx
Trying a different button position. What do you think?
> Copy to side ui

- src/components/Options/style.scss
- src/components/Output/index.tsx
- src/components/compress/style.scss
- src/components/intro/style.scss
- src/style/index.scss
Fixing a few little issues I saw while testing a Pixel C.
> Android tablet bugs

- package-lock.json
- src/components/intro/style.scss
Tiny fix to prevent the logo taking over the screen.
> Prevent logo taking over on smaller screens.

- webpack.config.js
> Fix build on Windows

- codecs/optipng/README.md
closes #367
updating incorrect URL
> Update README.md for OptiPNG

- src/components/compress/style.scss
I'm not 100% sure why this fixes the problem. I guess I don't fully understand the grid & flexbox algorithms. However, I created a [little reduction](https://static-misc.glitch.me/flexbox-issue-reduction/), and this one-line change fixes it.
> Fixing layout issue in #446

- src/codecs/rotate/processor.ts
Fixes #493 
(H/T @alisaitbilgi)
> Don’t use instantiateStreaming for rotate wasm module

- src/codecs/processor-worker/index.ts
This intentionally excludes time of loading corresponding modules, and only measures actual processing.
While this is not perfect as it's not integrated in the UI (cc @jakearchibald), it gives at least some way to measure performance of different codecs and their integrations on particular files.
> Add encoding/decoding times to console
